"""
testbench_generator.py
-----------------------
Generates a self-checking Verilator C++ testbench for a design under
evolution.

Design choice: rather than trying to parse arbitrary mutated Verilog ports
(fragile), EvoHDL fixes each supported module's port contract for the whole
run. Mutation/crossover operate on the *implementation* inside the module,
never on the interface. This keeps every generated design instantiable by
the same testbench, which is what makes an apples-to-apples fitness
comparison possible.

Every golden reference model lives in Python so we never need a second
Verilog "known-good" implementation to drift out of sync.

Multi-module support: `render_testbench(module_name, ...)` dispatches on
module_name to the matching renderer in MODULE_RENDERERS below. This is the
"extension point" the original alu_basic-only version of this file left
documented in designs/seed/comparator_4bit.v -- picorv32_alu.v is the first
design to actually use it, and it establishes the pattern for adding more
(e.g. wiring up comparator_4bit / counter_4bit the same way).
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Callable, List, Tuple

MODULE_NAME_PLACEHOLDER = "__MODULE_NAME__"

# ============================================================================
# alu_basic (original 8-bit ALU) -- unchanged from the original single-module
# version of this file.
# ============================================================================

ALU_BASIC_CPP_TEMPLATE = r"""
// AUTO-GENERATED by testbench_generator.py -- do not edit by hand.
#include <verilated.h>
#include "V__MODULE_NAME__.h"
#include <cstdio>
#include <cstdint>

struct Vector {
    uint8_t a;
    uint8_t b;
    uint8_t opcode;
    uint8_t expected_result;
    uint8_t expected_carry;
};

// {VECTORS}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    V__MODULE_NAME__* dut = new V__MODULE_NAME__;

    int total = sizeof(vectors) / sizeof(Vector);
    int passed = 0;

    for (int i = 0; i < total; i++) {
        dut->a = vectors[i].a;
        dut->b = vectors[i].b;
        dut->opcode = vectors[i].opcode;
        dut->eval();

        bool result_ok = (dut->result == vectors[i].expected_result);
        bool carry_ok  = (dut->carry_out == vectors[i].expected_carry);

        if (result_ok && carry_ok) {
            passed++;
        } else {
            fprintf(stderr,
                "MISMATCH vec=%d a=%d b=%d op=%d got_r=%d exp_r=%d got_c=%d exp_c=%d\n",
                i, vectors[i].a, vectors[i].b, vectors[i].opcode,
                dut->result, vectors[i].expected_result,
                dut->carry_out, vectors[i].expected_carry);
        }
    }

    printf("EVOHDL_RESULT passed=%d total=%d\n", passed, total);

    delete dut;
    return (passed == total) ? 0 : 1;
}
"""


def golden_alu(a: int, b: int, opcode: int) -> Tuple[int, int]:
    """Reference (correct-by-definition) ALU behaviour. Returns (result, carry)."""
    a &= 0xFF
    b &= 0xFF
    if opcode == 0b000:  # ADD
        total = a + b
        return total & 0xFF, 1 if total > 0xFF else 0
    if opcode == 0b001:  # SUB
        total = a - b
        return total & 0xFF, 1 if total < 0 else 0
    if opcode == 0b010:  # AND
        return a & b, 0
    if opcode == 0b011:  # OR
        return a | b, 0
    if opcode == 0b100:  # XOR
        return a ^ b, 0
    if opcode == 0b101:  # NOT A
        return (~a) & 0xFF, 0
    if opcode == 0b110:  # SHL
        return (a << 1) & 0xFF, 0
    if opcode == 0b111:  # SHR
        return (a >> 1) & 0xFF, 0
    return 0, 0


def _generate_alu_basic_vectors(num_random: int = 200, seed: int | None = None) -> List[Tuple[int, int, int, int, int]]:
    """
    Build directed corner-case vectors + random vectors.
    Returns list of (a, b, opcode, expected_result, expected_carry).
    """
    rng = random.Random(seed)
    vectors = []

    corner_values = [0x00, 0x01, 0x7F, 0x80, 0xFE, 0xFF]
    for opcode in range(8):
        for a in corner_values:
            for b in corner_values:
                r, c = golden_alu(a, b, opcode)
                vectors.append((a, b, opcode, r, c))

    for _ in range(num_random):
        a = rng.randint(0, 255)
        b = rng.randint(0, 255)
        opcode = rng.randint(0, 7)
        r, c = golden_alu(a, b, opcode)
        vectors.append((a, b, opcode, r, c))

    return vectors


def _render_alu_basic_testbench(module_name: str, num_random_vectors: int = 200, seed: int | None = 42) -> str:
    vectors = _generate_alu_basic_vectors(num_random_vectors, seed=seed)
    lines = ["static Vector vectors[] = {"]
    for (a, b, op, r, c) in vectors:
        lines.append(f"    {{{a}, {b}, {op}, {r}, {c}}},")
    lines.append("};")
    vector_block = "\n".join(lines)

    cpp = ALU_BASIC_CPP_TEMPLATE.replace("// {VECTORS}", vector_block)
    cpp = cpp.replace(MODULE_NAME_PLACEHOLDER, module_name)
    return cpp


# ============================================================================
# picorv32_alu -- real 32-bit RV32I ALU extracted from PicoRV32
# (see designs/seed/picorv32_alu.v for provenance / opcode encoding notes).
# ============================================================================

PICORV32_ALU_CPP_TEMPLATE = r"""
// AUTO-GENERATED by testbench_generator.py -- do not edit by hand.
#include <verilated.h>
#include "V__MODULE_NAME__.h"
#include <cstdio>
#include <cstdint>

struct Vector {
    uint32_t op1;
    uint32_t op2;
    uint8_t  alu_op;
    uint32_t expected;
};

// {VECTORS}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    V__MODULE_NAME__* dut = new V__MODULE_NAME__;

    int total = sizeof(vectors) / sizeof(Vector);
    int passed = 0;

    for (int i = 0; i < total; i++) {
        dut->reg_op1 = vectors[i].op1;
        dut->reg_op2 = vectors[i].op2;
        dut->alu_op  = vectors[i].alu_op;
        dut->eval();

        if (dut->alu_out == vectors[i].expected) {
            passed++;
        } else {
            fprintf(stderr,
                "MISMATCH vec=%d op1=%08x op2=%08x alu_op=%d got=%08x exp=%08x\n",
                i, vectors[i].op1, vectors[i].op2, vectors[i].alu_op,
                dut->alu_out, vectors[i].expected);
        }
    }

    printf("EVOHDL_RESULT passed=%d total=%d\n", passed, total);

    delete dut;
    return (passed == total) ? 0 : 1;
}
"""


def _sext32(x: int) -> int:
    x &= 0xFFFFFFFF
    return x - (1 << 32) if x & 0x80000000 else x


def golden_picorv32_alu(op1: int, op2: int, alu_op: int) -> int:
    """
    Reference model for picorv32_alu.v -- a line-for-line Python translation
    of the real PicoRV32 ALU datapath (see designs/seed/picorv32_alu.v
    header for the exact source lines this is extracted from). Returns the
    32-bit alu_out value.
    """
    op1 &= 0xFFFFFFFF
    op2 &= 0xFFFFFFFF
    shamt = op2 & 0x1F
    if alu_op == 0b0000:   # ADD
        return (op1 + op2) & 0xFFFFFFFF
    if alu_op == 0b0001:   # SUB
        return (op1 - op2) & 0xFFFFFFFF
    if alu_op == 0b0010:   # SLL
        return (op1 << shamt) & 0xFFFFFFFF
    if alu_op == 0b0011:   # SLT
        return 1 if _sext32(op1) < _sext32(op2) else 0
    if alu_op == 0b0100:   # SLTU
        return 1 if op1 < op2 else 0
    if alu_op == 0b0101:   # XOR
        return op1 ^ op2
    if alu_op == 0b0110:   # SRL
        return (op1 >> shamt) & 0xFFFFFFFF
    if alu_op == 0b0111:   # SRA
        return (_sext32(op1) >> shamt) & 0xFFFFFFFF
    if alu_op == 0b1000:   # OR
        return op1 | op2
    if alu_op == 0b1001:   # AND
        return op1 & op2
    return 0


def _generate_picorv32_alu_vectors(num_random: int = 200, seed: int | None = None) -> List[Tuple[int, int, int, int]]:
    rng = random.Random(seed)
    vectors = []

    corner_values = [0x00000000, 0x00000001, 0x7FFFFFFF, 0x80000000,
                      0xFFFFFFFE, 0xFFFFFFFF, 0x12345678, 0xDEADBEEF]
    for alu_op in range(10):  # 0000..1001, see designs/seed/picorv32_alu.v
        for a in corner_values:
            for b in corner_values:
                vectors.append((a, b, alu_op, golden_picorv32_alu(a, b, alu_op)))

    for _ in range(num_random):
        a = rng.randint(0, 2**32 - 1)
        b = rng.randint(0, 2**32 - 1)
        alu_op = rng.randint(0, 9)
        vectors.append((a, b, alu_op, golden_picorv32_alu(a, b, alu_op)))

    return vectors


def _render_picorv32_alu_testbench(module_name: str, num_random_vectors: int = 200, seed: int | None = 42) -> str:
    vectors = _generate_picorv32_alu_vectors(num_random_vectors, seed=seed)
    lines = ["static Vector vectors[] = {"]
    for (a, b, op, exp) in vectors:
        lines.append(f"    {{0x{a:08x}u, 0x{b:08x}u, {op}, 0x{exp:08x}u}},")
    lines.append("};")
    vector_block = "\n".join(lines)

    cpp = PICORV32_ALU_CPP_TEMPLATE.replace("// {VECTORS}", vector_block)
    cpp = cpp.replace(MODULE_NAME_PLACEHOLDER, module_name)
    return cpp


# ============================================================================
# counter_4bit (Stage-3 addition, 2026-09) -- the first SEQUENTIAL (clocked)
# design wired into the automated GA pipeline. Every other module above is
# purely combinational (dut->eval() once per test vector, no clock). A
# clocked design needs the C++ testbench to actually drive the clock edge by
# edge and check state *across* cycles, not just a single input/output pair
# -- that's the missing piece the README's "Current Limitations" flagged
# ("comparator_4bit.v and counter_4bit.v are left as the next extension
# points ... needs a testbench generator that drives a clock and checks
# state over multiple cycles").
#
# Pattern: drop clk low -> apply this cycle's (rst_n, en) -> eval() (lets
# Verilator settle any async-reset-triggered always block) -> raise clk
# high -> eval() (this is the posedge clk that the design's
# `always @(posedge clk or negedge rst_n)` block reacts to) -> compare
# count against the Python-computed golden value for that cycle.
# ============================================================================

COUNTER_4BIT_CPP_TEMPLATE = r"""
// AUTO-GENERATED by testbench_generator.py -- do not edit by hand.
// Sequential (clocked) testbench: drives clk/rst_n/en edge-by-edge and
// checks `count` after every rising edge against a golden cycle-by-cycle
// trace, instead of a single combinational input/output pair.
#include <verilated.h>
#include "V__MODULE_NAME__.h"
#include <cstdio>
#include <cstdint>

struct Cycle {
    uint8_t rst_n;
    uint8_t en;
    uint8_t expected_count;  // value of `count` right after this cycle's posedge
};

// {VECTORS}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    V__MODULE_NAME__* dut = new V__MODULE_NAME__;

    int total = sizeof(cycles) / sizeof(Cycle);
    int passed = 0;

    for (int i = 0; i < total; i++) {
        dut->clk = 0;
        dut->rst_n = cycles[i].rst_n;
        dut->en = cycles[i].en;
        dut->eval();   // let any async reset (negedge rst_n) settle first

        dut->clk = 1;
        dut->eval();   // posedge clk -- the design's clocked always-block fires

        bool ok = (dut->count == cycles[i].expected_count);
        if (ok) {
            passed++;
        } else {
            fprintf(stderr,
                "MISMATCH cycle=%d rst_n=%d en=%d got_count=%d exp_count=%d\n",
                i, cycles[i].rst_n, cycles[i].en,
                dut->count, cycles[i].expected_count);
        }
    }

    printf("EVOHDL_RESULT passed=%d total=%d\n", passed, total);

    delete dut;
    return (passed == total) ? 0 : 1;
}
"""


def golden_counter_4bit_step(rst_n: int, en: int, prev_count: int) -> int:
    """Reference (correct-by-definition) counter_4bit behaviour for one clock
    cycle. Mirrors the seed RTL's `always @(posedge clk or negedge rst_n)`
    exactly: async reset takes priority, else count up by 1 when en=1 and
    wraps 4 bits (15 -> 0), else holds."""
    if not rst_n:
        return 0
    if en:
        return (prev_count + 1) & 0xF
    return prev_count


def _generate_counter_4bit_vectors(num_random: int = 200, seed: int | None = None) -> List[Tuple[int, int, int]]:
    rng = random.Random(seed)
    cycles: List[Tuple[int, int, int]] = []
    count = 0

    def step(rst_n: int, en: int):
        nonlocal count
        count = golden_counter_4bit_step(rst_n, en, count)
        cycles.append((rst_n, en, count))

    # -- Directed corner cases first (deterministic, always included) --
    step(0, 0)                                   # reset asserted, held
    for _ in range(20):
        step(1, 1)                               # straight count-up
    step(1, 0)                                    # hold: en=0 freezes count
    step(1, 0)
    step(1, 0)
    step(0, 1)                                    # async reset overrides en=1
    for _ in range(16):
        step(1, 1)                               # count 0..15 and wrap past 15 -> 0
    step(0, 0)                                    # reset again mid-sequence
    step(1, 1)

    # -- Randomized coverage for the remainder --
    while len(cycles) < num_random:
        rst_n = 0 if rng.random() < 0.05 else 1   # occasional reset pulses
        en = rng.randint(0, 1)
        step(rst_n, en)

    return cycles


def _render_counter_4bit_testbench(module_name: str, num_random_vectors: int = 200, seed: int | None = 42) -> str:
    cycles = _generate_counter_4bit_vectors(num_random_vectors, seed=seed)
    lines = ["static Cycle cycles[] = {"]
    for (rst_n, en, expected) in cycles:
        lines.append(f"    {{{rst_n}, {en}, {expected}}},")
    lines.append("};")
    vector_block = "\n".join(lines)

    cpp = COUNTER_4BIT_CPP_TEMPLATE.replace("// {VECTORS}", vector_block)
    cpp = cpp.replace(MODULE_NAME_PLACEHOLDER, module_name)
    return cpp


# ============================================================================
# Dispatch registry -- add a new (renderer) entry here to support another
# seed design, following the pattern documented in designs/seed/comparator_4bit.v.
# ============================================================================

RendererFn = Callable[[str, int, int | None], str]

MODULE_RENDERERS: dict[str, RendererFn] = {
    "alu_basic": _render_alu_basic_testbench,
    "picorv32_alu": _render_picorv32_alu_testbench,
    "counter_4bit": _render_counter_4bit_testbench,
}


def render_testbench(module_name: str, num_random_vectors: int = 200, seed: int | None = 42) -> str:
    renderer = MODULE_RENDERERS.get(module_name)
    if renderer is None:
        raise ValueError(
            f"No testbench renderer registered for module_name={module_name!r}. "
            f"Known modules: {sorted(MODULE_RENDERERS)}. "
            f"Add a golden model + CPP template + renderer here to support a new module "
            f"(see designs/seed/comparator_4bit.v for the extension recipe)."
        )
    return renderer(module_name, num_random_vectors, seed)


def write_testbench(module_name: str, out_path: str | Path, num_random_vectors: int = 200, seed: int | None = 42) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_testbench(module_name, num_random_vectors, seed))
    return out_path


# Backward-compat alias -- the original single-module version of this file
# exposed `generate_vectors` as the public name for what is now
# `_generate_alu_basic_vectors` (renamed once a second module needed its
# own generator). Existing tests/callers import `generate_vectors` directly.
generate_vectors = _generate_alu_basic_vectors


if __name__ == "__main__":
    p = write_testbench("alu_basic", "/tmp/evohdl_tb_demo.cpp")
    print(f"Wrote demo testbench to {p}")
    p2 = write_testbench("picorv32_alu", "/tmp/evohdl_tb_picorv32_alu_demo.cpp")
    print(f"Wrote demo testbench to {p2}")
